"$schema" = 'https://starship.rs/config-schema.json'

format = " [](fg:red)$username[](bg:red fg:#FFCA5C)$directory[ ](fg:#FFCA5C)$git_branch$git_status$all$character"

[username]
show_always = true
format = '[$user ](bg:red fg:black)'
disabled = false

[directory]
format = '[$path](fg:#1e1e2e bg:#FFCA5C)'
style = 'fg:#1e1e2e bg:#FFCA5C'
truncation_length = 3
truncate_to_repo = false
home_symbol = '~'

[git_branch]
format = '[](#cba6f7)[ 󰘬 $branch ](fg:#1e1e2e bg:#cba6f7)[](#cba6f7)'
style = 'fg:#1e1e2e bg:#cba6f7'

[git_status]
format = '[](#f38ba8)[ $all_status$ahead_behind ](fg:#1e1e2e bg:#f38ba8)[](#f38ba8)'
style = 'fg:#1e1e2e bg:#f38ba8'

[python]
symbol = "  "
format = '[$symbol($version)]($style)'
style = 'fg:#89dceb'

[nodejs]
format = '[  $version ](fg:#1e1e2e bg:#a6e3a1)'
style = 'fg:#1e1e2e bg:#a6e3a1'

[character]
format = ' [❯](bold #ebe9e9) '
success_symbol = '[❯](bold #a7f7a0)'
error_symbol = '[❯](bold #ff6b6b)'
